# Numpy Array Basics

In [1]:
# Importing the numpy library
import numpy as np

print("Numpy library imported successfully")

Numpy library imported successfully


## Creating a numpy array

### Using Built in Data Structures in Python

In [2]:
# Initializing lists
my_list = [2, 3, 4, 5, 8]
print(my_list)

[2, 3, 4, 5, 8]


In [3]:
# Creating numpy array using lists
np.array(my_list)

array([2, 3, 4, 5, 8])

In [4]:
# Initilazing a matrix 
my_matrix = [[1,2,3], [4,5,6], [7,8,9]]
print(my_matrix)

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]


In [5]:
# Creating array using a matrix
np.array(my_matrix)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

### Built methods
Lots of Built in methods are available to create  a numpy array

### Using arange()
Returns evenly spaced values in the given interval

In [6]:
# using arange function

np.arange(30)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [7]:
# Using the additional parameter step
np.arange(20, step = 2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

### Zeroes and Ones
Generate a array of zeros and ones


Returns an array of float values

In [8]:
# Using zeroes function
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [9]:
# Using ones function
np.ones(5)

array([1., 1., 1., 1., 1.])

## Linespace

Returns evenly spaced numbers in the specified interval

In [10]:
# The start index is 0 and the stop index is 10
np.linspace(0, 10)

array([ 0.        ,  0.20408163,  0.40816327,  0.6122449 ,  0.81632653,
        1.02040816,  1.2244898 ,  1.42857143,  1.63265306,  1.83673469,
        2.04081633,  2.24489796,  2.44897959,  2.65306122,  2.85714286,
        3.06122449,  3.26530612,  3.46938776,  3.67346939,  3.87755102,
        4.08163265,  4.28571429,  4.48979592,  4.69387755,  4.89795918,
        5.10204082,  5.30612245,  5.51020408,  5.71428571,  5.91836735,
        6.12244898,  6.32653061,  6.53061224,  6.73469388,  6.93877551,
        7.14285714,  7.34693878,  7.55102041,  7.75510204,  7.95918367,
        8.16326531,  8.36734694,  8.57142857,  8.7755102 ,  8.97959184,
        9.18367347,  9.3877551 ,  9.59183673,  9.79591837, 10.        ])

In [11]:
# Using an additional arguement step 
np.linspace(0,10, 10)

array([ 0.        ,  1.11111111,  2.22222222,  3.33333333,  4.44444444,
        5.55555556,  6.66666667,  7.77777778,  8.88888889, 10.        ])

## eye

Creates an identity matrix

In [12]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

## Random

Numpy offers a lot of ways to create random arrays

### rand

Create an array of given shape and populate it with random samples from the distribution over [0, 1)

Returns a uniform distribution of sample numbers

In [13]:
# The range of the numbers is always between 0 and 1
np.random.rand(5)

array([0.72742022, 0.52018947, 0.0289695 , 0.8487835 , 0.04561596])

In [14]:
np.random.rand(3, 3)

array([[0.90157344, 0.39756653, 0.14594351],
       [0.7724601 , 0.98164803, 0.81375861],
       [0.70901436, 0.37932127, 0.61934348]])

### randn

Returns a sample(or samples) from a "standard Normal Distribution"

In [15]:
np.random.randn(3)

array([-1.39229618, -0.70541407, -0.02301432])

In [16]:
np.random.randn(5,5)

array([[ 0.66140145, -0.09054358,  1.41773266,  0.46107149,  0.23905315],
       [-0.97854644,  0.47879596, -0.28127946, -0.81180959, -0.66203863],
       [ 0.97576933, -0.0769162 , -1.32235339, -0.04436403,  0.241798  ],
       [ 1.56162659, -0.98641346,  0.24606362, -0.52065478,  1.01361858],
       [-0.80154083,  1.14460922,  0.89258521,  1.93429173, -0.1292324 ]])

## randint

Random integers from low(inclusive) to high(exclusive)

In [17]:
# Just returns one element from the range
np.random.randint(5, 25)

8

In [18]:
# Returns multiple elements from the range
np.random.randint(5, 25, 10)

array([10, 13,  5, 17, 12, 24, 24, 17, 13, 20])

### Checking the data type of a numpy array

### To get the data type of the object inside the array use dtype: arr.dtype

In [19]:
x = np.arange(20, 4)
type(x)

numpy.ndarray

In [20]:
y = np.random.randint(4, 50, 5)
type(y)

numpy.ndarray

In [21]:
x.dtype

dtype('int32')

In [22]:
y.dtype

dtype('int32')

In [23]:
z = np.random.randn(3)
z.dtype

dtype('float64')

## Array attribute and methods: Reshape

Returns the same array with same data with new shape. Note: the data should remain the same

In [24]:
a = np.random.rand(1, 100).reshape(4, 25)
a

array([[0.46807258, 0.52096253, 0.09166906, 0.79133328, 0.83794832,
        0.63358526, 0.44108016, 0.76664262, 0.33162133, 0.6687428 ,
        0.99420979, 0.10090514, 0.14951778, 0.5883546 , 0.58320754,
        0.57049929, 0.04793669, 0.07376361, 0.98381539, 0.50812231,
        0.24274215, 0.23669132, 0.74094697, 0.67210216, 0.21971236],
       [0.71174688, 0.73977524, 0.96768192, 0.67419408, 0.94651478,
        0.93658281, 0.39133826, 0.76447486, 0.38859405, 0.01328543,
        0.19631472, 0.65286263, 0.80334244, 0.6880865 , 0.94760468,
        0.63436949, 0.82862594, 0.58798481, 0.12405833, 0.91014069,
        0.83770316, 0.98682864, 0.51695279, 0.49094999, 0.14284317],
       [0.7940748 , 0.73757369, 0.43036009, 0.55213221, 0.91686903,
        0.93933089, 0.89827548, 0.35916277, 0.22032145, 0.65368174,
        0.2319447 , 0.37602472, 0.63264338, 0.34771733, 0.6202181 ,
        0.70538847, 0.53938637, 0.61909609, 0.20200798, 0.9171148 ,
        0.62813746, 0.16054587, 0.68602225, 0.

## min, max, argmin, argmax

min, max - used to find the minimum and the maximum values respectively

argmin, argmax - used to find the postions of the minimum and the maximum values respectively

In [25]:
arr = np.random.randint(0, 50, 10)
arr

array([34, 23,  1,  6, 21, 12,  5, 15, 36, 11])

In [26]:
# To get the minimum value in the array arr
arr.min()

1

In [27]:
# To extract the maximum value in the array arr
arr.max()

36

In [28]:
# To extract the position of the minimum value in the array arr
arr.argmin()

2

In [29]:
# To extract the position of the maximum value in the array arr
arr.argmax()

8

## Shape of an array

In [30]:
arr

array([34, 23,  1,  6, 21, 12,  5, 15, 36, 11])

In [31]:
arr.shape

(10,)

In [32]:
y = arr.reshape(2, 5)
y

array([[34, 23,  1,  6, 21],
       [12,  5, 15, 36, 11]])

In [33]:
y.shape

(2, 5)