# Numpy Operations

## Arithematic Operations on a numpy array

In [1]:
# Importing the numpy library
import numpy as np

print("Import Successful")

Import Successful


In [3]:
# Create 2 array to perform operations

arr1 = np.random.randint(35, 100, 15)
arr2 = np.random.randint(35, 100, 15)

# Print the  2 arrays
print("arr1:" , arr1)
print("arr2:", arr2)

arr1: [63 64 69 79 50 54 68 70 42 99 75 95 64 48 88]
arr2: [45 38 78 52 44 88 58 96 87 65 76 49 44 50 65]


## Vectorization operations

Performing Addition, Subtraction, Division and Multiplication on a numpy array results into a vectorization operation

#### Division operation raises a warning for division by zero error instead of a error

Each element of the first array gets added, subtracted, divided or multiplied with each element of the second array. This is called Vectorization Operations of arrays

In [4]:
# Adding the 2 arrays
arr1 + arr2

array([108, 102, 147, 131,  94, 142, 126, 166, 129, 164, 151, 144, 108,
        98, 153])

In [5]:
# Subtracting 2 arrays
arr1 - arr2

array([ 18,  26,  -9,  27,   6, -34,  10, -26, -45,  34,  -1,  46,  20,
        -2,  23])

In [6]:
# Multiplying 2 arrays
arr1 * arr2

array([2835, 2432, 5382, 4108, 2200, 4752, 3944, 6720, 3654, 6435, 5700,
       4655, 2816, 2400, 5720])

In [7]:
# Dividing 2 arrays
arr1 / arr2

array([1.4       , 1.68421053, 0.88461538, 1.51923077, 1.13636364,
       0.61363636, 1.17241379, 0.72916667, 0.48275862, 1.52307692,
       0.98684211, 1.93877551, 1.45454545, 0.96      , 1.35384615])

### Broadcasting Operation on a numpy array

Broadcasting is when a scalar is added, subtracted, multiplied or divided to numpy array each element of the array gets added, subtracted, multiplied or divided with the scalar number.

In [8]:
arr1 * 2

array([126, 128, 138, 158, 100, 108, 136, 140,  84, 198, 150, 190, 128,
        96, 176])

In [9]:
arr2 + 5

array([ 50,  43,  83,  57,  49,  93,  63, 101,  92,  70,  81,  54,  49,
        55,  70])

In [10]:
arr1 / 2

array([31.5, 32. , 34.5, 39.5, 25. , 27. , 34. , 35. , 21. , 49.5, 37.5,
       47.5, 32. , 24. , 44. ])

In [11]:
arr2 - 20

array([25, 18, 58, 32, 24, 68, 38, 76, 67, 45, 56, 29, 24, 30, 45])