# Numpy Indexing and Selection

Here we will look at how to extract elements or a group of elements from a numpy array

In [1]:
# Importing the numpy library
import numpy as np

print("Import Successful")

Import Successful


In [2]:
# Creating a sample array
arr = np.arange(30)

# Print
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

### Bracket Indexing and Selection

The simplest way to pick one or more elements of an array is similar to Python lists.

#### Get a value at an index


In [3]:
# Getting the value at 25th position of arr
arr[25]

25

In [4]:
# Getting the value at 8th position of arr
arr[8]

8

In [5]:
# Getting the value at 31st position of arr
arr[31]

IndexError: index 31 is out of bounds for axis 0 with size 30

#### Get a value in range

In [6]:
arr[2:5]

array([2, 3, 4])

In [7]:
arr[10:25]

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24])

In [8]:
arr[10:35]

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29])

### Broadcasting 

Numpy differ from python lists because of their ability to broadcast

Array broadcast applies the value to entire array 

In [9]:
# Broadcast to all the 30 values of the array arr
arr[:] = 5
arr

array([5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5,
       5, 5, 5, 5, 5, 5, 5, 5])

In [10]:
# List Broadcast produces an error
lis = [2, 3,4, 5]
lis[:] = 5

TypeError: can only assign an iterable

## Indexing a 2D array

The general format is arr_2d[row][col] or arr_2d[row,col]. the former one is recommended

In [11]:
# Creating a 2D array using the numpy 
arr = np.random.randint(0,100,30).reshape(5, 6)

# print
arr

array([[90, 81, 37, 82, 90,  9],
       [63, 62, 59, 37, 62, 76],
       [21, 67, 52, 89, 47, 68],
       [90, 65, 42, 66,  3, 34],
       [94, 80,  2,  9, 51, 79]])

In [12]:
arr[4][2]

2

In [13]:
arr[4, 2]

2

In [14]:
# Slicing all the rows except the 0th column
arr[:, 1:]

array([[81, 37, 82, 90,  9],
       [62, 59, 37, 62, 76],
       [67, 52, 89, 47, 68],
       [65, 42, 66,  3, 34],
       [80,  2,  9, 51, 79]])

In [15]:
# Slicing rows from 3rd row and columns from 2nd column
arr[2:, 3:]

array([[89, 47, 68],
       [66,  3, 34],
       [ 9, 51, 79]])

## Selection

In [16]:
# Creating a numpy array
sal = np.random.randint(1000, 2000, 50)

In [17]:
# Selecting based on a condition
sum(sal > sal.mean())

27

In [18]:
# Creating a numpy array
arr = np.arange(0,11)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [19]:
# Selecting even numbers and calculating their sum
sum(arr % 2 == 0)

6

In [20]:
# Comparision operator returns boolean array
arr > 4

array([False, False, False, False, False,  True,  True,  True,  True,
        True,  True])

In [21]:
# Selection based on a condition
bool_arr = arr > 4
arr[bool_arr]

array([ 5,  6,  7,  8,  9, 10])

In [22]:
arr[arr > 4]

array([ 5,  6,  7,  8,  9, 10])

In [23]:
x = 2
arr[arr > 2]

array([ 3,  4,  5,  6,  7,  8,  9, 10])